# Лабораторная работа №2 Основы работы с библиотекой NumPy

# Вариант №5
---



# 1. Создание и изменение массивов
Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.Выведите итоговый массив.

In [216]:
import numpy as np

arr = np.matrix('1 2 3; 4 5 6; 7 8 9')

arr = arr*2
arr[arr > 10] = 0

print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


# 2. Работа с булевыми масками
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [217]:
import numpy as np

arr = np.random.randint(1, 101, 20)
print(arr)

print(arr[arr % 5 == 0])
arr[arr % 5 == 0] = -1

print(arr)

[44 93 44 42 65 88 14 63 63  8 88 44 17 29 87 59 54  1  9 57]
[65]
[44 93 44 42 -1 88 14 63 63  8 88 44 17 29 87 59 54  1  9 57]


# 3. Объединение и разбиение массивов
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.


*   Объедините эти массивы в один двумерный массив (по строкам).
*   Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.

In [38]:
import numpy as np

arr1 = np.random.randint(1, 51, 5)
arr2 = np.random.randint(1, 51, 5)
print(arr1, arr2)

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

arr4, arr5 = np.hsplit(arr3, 2)
print(arr4, arr5)

[50 20 44 35 45] [14 35 43 12 37]
[50 20 44 35 45 14 35 43 12 37]
[50 20 44 35 45] [14 35 43 12 37]


# 4. Генерация и работа с линейными последовательностями

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [218]:
import numpy as np

arr1 = np.random.randint(-10, 10, 50)
print(arr1)
sum_p = arr1[arr1 > 0].sum()
sum_n = arr1[arr1 < 0].sum()


print("Cумма положительных: ",sum_p)
print("Cумма отрицательных: ",sum_n)

[-10  -3  -9   3   6  -8   1   3   6   2  -9 -10  -5   9 -10   0   7   2
   8 -10  -9   0 -10  -4  -6  -6  -5   4   6   5  -6  -9  -3   3  -9 -10
  -6   3   0   2  -8  -4  -5  -4   2  -4  -9   6   9   7]
Cумма положительных:  94
Cумма отрицательных:  -191


# 5. Работа с диагональнами и единичными матрицами
Создайте:

*   Единичную матрицу размером 4×4.
*   Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [219]:
import numpy as np

m1 = np.eye(4)
print(f"Единичная матрица: \n{m1}")

arr = np.array([5, 10, 15, 20])

m2 = np.diag(arr)
print(f"Диагональная матрица: \n {m2}")

compare = '>' if m1.sum() > m2.sum() else '<'
print(f"{m1.sum()} {compare} {m2.sum()}")

Единичная матрица: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица: 
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
4.0 < 50


# 6. Создание и базовые операции с матрицами
Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:


*   Их сумму
*   Их разность
*   Их поэлементное произведение




In [220]:
import numpy as np

m1 = np.random.randint(1, 21, (3, 3))
m2 = np.random.randint(1, 21, (3, 3))

print(f"{m1}\n")
print(f"{m2}\n")
print(f"Cумма: \n", m1+m2, "\n")
print(f"Разность: \n", m1-m2, "\n")
print(f"Поэлементное произведение: \n", m1*m2, "\n")

[[19  3  5]
 [10 12  9]
 [ 2  5  7]]

[[ 3 20 11]
 [20 14 19]
 [ 7 18  5]]

Cумма: 
 [[22 23 16]
 [30 26 28]
 [ 9 23 12]] 

Разность: 
 [[ 16 -17  -6]
 [-10  -2 -10]
 [ -5 -13   2]] 

Поэлементное произведение: 
 [[ 57  60  55]
 [200 168 171]
 [ 14  90  35]] 



# 7. Умножение матриц

Создайте две матрицы NumPy:

*   Первую размером 2×3 заполненную случайными числами от 1 до 10.
*   Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение ( @ или пр.dot ) и выведите результат.

In [153]:
import numpy as np

m1 = np.random.randint(1, 10, (2, 3))
m2 = np.random.randint(1, 10, (3, 2))
print(m1, "\n")
print(m2, "\n")

mult = np.dot(m1, m2)

print(f"Произведение матриц: \n",mult, "\n")


[[5 3 5]
 [2 9 4]] 

[[8 9]
 [7 2]
 [3 4]] 

Произведение матриц: 
 [[76 71]
 [91 52]] 



# 8. Определитель и обратная матрица

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:

*   Определитель этой матрицы
*   Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)


Используйте функции nр.linalg.det и nр.linalg.inv.

In [230]:
import numpy as np

# 1. Генерация случайной матрицы 3×3
m1 = np.random.randint(1, 10, (3, 3))
print("Сгенерированная матрица:")
print(m1)

# 2. Вычисление определителя
det = np.linalg.det(m1)
print(f"Определитель матрицы: {det:.2f}")

# 3. Проверка на вырожденность и вычисление обратной матрицы
if np.isclose(det, 0):
    print("Матрица вырождена (определитель равен 0), обратной матрицы не существует")
else:
    inv_matrix = np.linalg.inv(m1)
    print("\nОбратная матрица:")
    print(inv_matrix)



Сгенерированная матрица:
[[8 6 4]
 [4 1 6]
 [6 9 6]]
Определитель матрицы: -192.00

Обратная матрица:
[[ 0.25        0.         -0.16666667]
 [-0.0625     -0.125       0.16666667]
 [-0.15625     0.1875      0.08333333]]


# 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:

*   Исходную матрицу
*   Транспонированную матрицу
*   След матрицы (сумму элементов на главной диагонали)

Используйте пр. trace для нахождения следа.

In [232]:
import numpy as np

m1 = np.random.randint(1, 51, (4, 4))
mt = m1.T
sum = np.diag(m1).sum()



print("Исходная матрица: \n ", m1, "\n")
print("Транспонированная матрица: \n ", mt, "\n")
print("Cумма элементов на главной диагонали: \n ", m2, "\n")

Исходная матрица: 
  [[ 5 47 47 45]
 [38 43  6 13]
 [36 48 46 47]
 [ 1 17  6 37]] 

Транспонированная матрица: 
  [[ 5 38 36  1]
 [47 43 48 17]
 [47  6 46  6]
 [45 13 47 37]] 

Cумма элементов на главной диагонали: 
  [[ 3 20 11]
 [20 14 19]
 [ 7 18  5]] 



# 10. Системы линейных уравнений
Решите систему линейных уравнений вида:
\[
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2z = 6 \\
-3x + 5y + 4z = 2
\end{cases}
\]

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат

In [231]:
import numpy as np


A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

B = np.array([5, 6, 2])

x = np.linalg.solve(A, B)

print("Решение системы:")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")
print(f"z = {x[2]:.2f}")

Решение системы:
x = 1.46
y = 0.86
z = 0.51


# 11. Индивидуальное задание
Решите индивидуальное задание согласно варианта. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

# Условие задачи:
5. Распределение нагрузки на работников. Три сотрудника должны выполнить 100 задач. Второй сотрудник должен выполнить на 10 задач больше, чем первый, а третий - в два раза больше, чем второй. Сколько задач получит каждый сотрудник?

In [214]:
import numpy as np

total_tasks = 100
A = np.array([
    [1, 1, 1],    # x + y + z = 100
    [-1, 1, 0],    # y = x + 10 → -x + y = 10
    [0, -2, 1]     # z = 2y → -2y + z = 0
])
B = np.array([100, 10, 0])

# 1. Решение методом Крамера
def cramer(A, B):
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Матрица вырождена, система не имеет единственного решения")
    solutions = []
    for i in range(A.shape[0]):
        Ai = A.copy()
        Ai[:, i] = B
        solutions.append(np.linalg.det(Ai) / det_A)
    return np.array(solutions)

cramer_solution = cramer(A, B)
print("Метод Крамера:", cramer_solution)

# 2. Решение матричным методом
def matrix_method(A, B):
    if np.linalg.det(A) == 0:
        print("Матрица вырождена, система не имеет единственного решения")
    A_inv = np.linalg.inv(A)
    solutions = np.dot(A_inv, B)
    return solutions   #

matrix_solution = matrix_method(A, B)
print("Матричный метод:", matrix_solution)

# 3. Решение с помощью np.linalg.solve
try:
    solve_solution = np.linalg.solve(A, B)
    print("np.linalg.solve:", solve_solution)
except np.linalg.LinAlgError:
    print("Матрица вырождена, система не имеет единственного решения")


Метод Крамера: [17.5 27.5 55. ]
Матричный метод: [17.5 27.5 55. ]
np.linalg.solve: [17.5 27.5 55. ]
