# Лабораторная работа №2 Основы работы с библиотекой NumPy

# Вариант №5
---



# Примеры использования библиотки Numpy:
---

# Создание массива:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])

# Операции с массивами:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]

# Матричные операции:





In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение

# Статистические функции

In [ ]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) # Стандартное отклонение

# Поддержка векторизации

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2 # Быстрое поэлементное умножение

# Доступ к элементам массива

In [ ]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


# Непрерывная часть массива

In [ ]:
m[0:2, 1:3]



# np.zeros(), np.eye()

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.ravel()

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.meshgrid()

In [ ]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 2, 5)
xg, yg = np.meshgrid(x, y)
xg


array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

# Вектор

In [ ]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


# Нулевой вектор-столбец

In [ ]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


# Единичный вектор-столбец

In [ ]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


# Диагональная матрица

In [ ]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


# Единичная матрица

In [ ]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Задание матрицы в общем виде

In [ ]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


# Транспонирование матрицы

In [ ]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

A_t = A.transpose()
print(A_t)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Сложение матриц

In [ ]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)



[[ 9  7  8]
 [14 11 19]]


# Обратная матрица

In [ ]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


# Ранг матрицы

In [ ]:
m_eye = np.eye(4)
print(m_eye)
rank = np.linalg.matrix_rank(m_eye)
print(rank)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4
